id: P004557
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:35.561898
source_metadata:
  id: bdr:W00KG03567
  title: བརྡའ་ཡིག་མིང་དོན་གསལ་བར་བྱེད་པའི་ཟླ་བའི་འོད་སྣང
  author: ''
  volumes:
    7424c7a1d114408ea60a75bda75ee38e:
      image_group_id: I00KG03585
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
